version: '3.7'
volumes:
  mock-server-config:

services:
  db:
    build:
      context: ../../db
    ports:
    - "5432:5432"
  loan:
    build:
      context: ../loan-server
    ports:
    - "8080:8080"
    command: java -jar loan.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loans
      INTEREST_RATE_URL: http://mock-server:8080/
    depends_on:
    - "db"
  mock-server:
    image: rodolpheche/wiremock:2.25.1
    ports:
      -  "8081:8080"
    volumes:
      - ../loan-acceptance-test/src/test/resources/wiremock-config:/home/wiremock
